### ISSUE TITLE
Run linter on typipng

### ISSUE THREAD

**Issue by ds-codemag** [adamwalzer/vscode-scss-lint#16]
Is it possible to run linter on typing or only on save?

**Comment by adamwalzer** [comment]
It is currently only possible to run this extension on save, but I will look into what it would mean to change that.

**Comment by adamwalzer** [comment]
Ask and you shall receive. The next version of the extension has the config `runOnTextChange` which defaults to `false` but if changed to `true` will run the extension on text changes. Let me know if it all works well for you. :-) and then we can close this issue.

**Comment by adamwalzer** [comment]
@freszyk is this feature working for you?

**Comment by ds-codemag** [comment]
Sorry for late answering. Now I have problem with run scss-lint. I put scss-lint.yml to main project folder and set "scssLint.configDir": "./" and I have "Error running scss-lint". It worked before.

**Comment by adamwalzer** [comment]
@freszyk I'm not sure why that would be breaking anything, but if .scss-lint.yaml is in your project's base directory, you shouldn't need to set `scssLint.configDir` at all. You can delete that from you settings json, and it should work. Let me know if that works. Thanks!

**Comment by freszyk** [comment]
I dont know why but it still doesnt work

**Comment by ds-codemag** [comment]
I made everythinx exactly how you wrote and still nothing.

**Comment by ds-codemag** [comment]
![obraz](https://user-images.githubusercontent.com/3948456/35872930-8a475576-0b68-11e8-9dd1-b89fa5b53881.png)
On the left is structure of my prject and on the right is opened file which should be validated but it isnt.

This is settings.json:
![obraz](https://user-images.githubusercontent.com/3948456/35872993-b8838630-0b68-11e8-9590-f5a840252388.png)

**Comment by adamwalzer** [comment]
Unfortunately, I can't quickly determine what's going on here. After work, I'll have to try to debug on a windows machine unless you'd be interested in debugging. I've never developed on a windows machine so I'll see how smoothly that all goes.

**Comment by adamwalzer** [comment]
Thanks for all the information. I believe I have fixed the issues. Let me know if everything is working for you. Thanks!

**Comment by ds-codemag** [comment]
Ok, something happens but still does'nt work. Now I have this error:
![obraz](https://user-images.githubusercontent.com/3948456/35999474-3f7f76a4-0d20-11e8-93e0-e9eb5ff59006.png)

**Comment by adamwalzer** [comment]
Ok. I'm trying to figure this out but I'm not all too familiar with shell on windows. Does your file path have spaces in it? Will I need to escape those? With `^`? Also, do you know if that double `\` before .scss-lint.yaml is an issue? I don't know windows well so I'm not familiar with if that's necessary for files starting with `.`. I should be able to fix any of those issues. (Hopefully those are the issues and not something I'm not thinking of.) I wasn't getting the double `\` issue on my windows machine but I can just only remove it if it exists. As far as the spaces are concerned, it'll be easy enough for me to just add spaces to my test directory. Based on the fact that it is giving us the full path, I'm thinking the issue is the double `\` because if the spaces were an issue it would be because windows thought the path was over before it was. Just thinking aloud here just so you can let me know if any of my logic is flawed. Thanks.

**Comment by ds-codemag** [comment]
I edited your code and removed double "\\". I thought that problem is with "file://" and replaced it to "C:" to get "C:\Users\User\Desktop\Projekty\Struktura nowego projektu\.scss-lint.yml" and it still dont work. I dont know what to do with that. I give up.

**Comment by ds-codemag** [comment]
You had right! I removed spaces from main directory and it works. OMG!
Reading the error, I would never have thought that spaces would cause error.

**Comment by adamwalzer** [comment]
I just published a new version of the extension that should resolve the space in path issue in case you want to keep using spaces in your path. Let me know if it works for you.

**Comment by ds-codemag** [comment]
Ok I'll check this after work.

**Comment by adamwalzer** [comment]
Ok. I'm going to assume this issue is resolved since I tested it myself, but please let me know if it isn't working for you. Thanks!
